# The URL the site will be built for
base_url = "https://pksunkara.com"

title = "pksunkara"
description = "My personal blog"
author = "Pavan Sunkara"

generate_feeds = true

# TODO: hide author page from main feed
taxonomies = [
	{ name = "tags", paginate_by = 10, feed = true },
	{ name = "series", feed = true },
]

[markdown.highlighting]
error_on_missing_language = true
light_theme = "one-light"
dark_theme = "one-dark-pro"

[extra]
github = "pksunkara"
linkedin = "pksunkara"
bluesky = "pksunkara.com"

google_analytics = "UA-9209860-4"

[extra.series.reign-whiteboarding]
title = "Reign: Whiteboarding a web framework"
status = "ongoing"
description = "Let's whiteboard on how to build the best web framework. We will talk about all the components needed for it and how they should work to achieve the best performance and developer experience."

[extra.series.jujutsu-tips-and-tricks]
title = "Jujutsu: Tips & Tricks"
status = "ongoing"
description = "A collection of tips and tricks to get the most out of Jujutsu. In this series, we will explore various features and workflows to either help you become more productive with Jujutsu or try to replicate some obscure Git workflows."
chronological = false
